config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'blogs/new' => 'blogs#new'
  post 'blogs' => "blogs#create"
  get 'top' => 'blogs#top'
  get 'blogs' => 'blogs#index'
  get 'blogs/:id' => 'blogs#show', as:'blog'
  get 'blogs/:id/edit' => 'blogs#edit', as:'edit_blog'
  patch 'blogs/:id' => 'blogs#update', as:'update_blog'
  delete 'blogs/:id' => 'blogs#destroy', as:'destroy_blog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  attachment :image
  
  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  def top
  end
  
  def new
    @blog = Blog.new
  end
  
  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blog_path(@blog.id)
    else
      render :new
    end
  end
  
  def index
    @blogs = Blog.all
  end
  
  def show
    @blog = Blog.find(params[:id])
  end
  
  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    blog = Blog.find(params[:id])
    blog.update(blog_params)
    redirect_to blog_path(blog.id)
  end
  
  def destroy
    blog = Blog.find(params[:id])
    blog.destroy
    redirect_to blogs_path
  end
  
  private
  def blog_params
    params.require(:blog).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<h1>編集画面だよ</h1>
<%= form_with model:@blog, url:"/blogs/#{@blog.id}", local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '保存' %>
<% end %>

app/views/blogs/index.html.erb
<h1>一覧画面</h1>

<%= @blogs.each do |blog| %>
  <p>タイトル</p>
  
  <span><%= link_to blog.title, blog_path(blog.id) %></span>
  <p>画像</p>
  <%= attachment_image_tag blog, :image, :fill, 100, 100, format: 'jpeg' %>
<% end %>

app/views/blogs/new.html.erb
<h1>ここから投稿してね★</h1>
<% if @blog.errors.any? %>
 <%= @blog.errors.count %>件のエラーが発生しました
 <%= @blog.errors.full_messages.each do |message| %>
  <%= message %>
 <% end %>
<% end %>

<%= form_with model:@blog, url:'/blogs', local:true do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <h4>画像</h4>
    <%= f.attachment_field :image %>
    <%= f.submit '投稿' %>
<% end %>

app/views/blogs/show.html.erb
<h1>詳細画面</h1>
<h4>タイトル</h4>
<p><%= @blog.title %></p>
<h4>本文</h4>
<p><%= @blog.body %></p>
<h4>画像</h4>
<%= attachment_image_tag @blog, :image, :fill, 300, 300, format: 'jpeg' %>
<%= link_to "編集", edit_blog_path(@blog.id) %>
<%= link_to "削除", destroy_blog_path(@blog.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

app/views/blogs/top.html.erb
<h1>トップページだよ😊</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>